# Generated by Django 4.1.6 on 2023-02-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_delete_choices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Choices',
        ),
    ]
